version: '3.8'

services:
  fomc-classifier:
    build: .
    ports:
      - "8501:8501"  # Streamlit frontend
      - "8000:8000"  # FastAPI backend
    volumes:
      - ./data:/app/data      # Mount your data directory
    environment:
      - EXCEL_PATH=/app/data/Sentiment&Attributes_Classification.xlsx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

